#!/bin/sh

#
# Set the sound outputs the way they should.
#

case "$1" in
  start)
	modprobe -v ath9k_htc
	printf "Setting sound... "

	echo -n " line - "
	amixer --quiet sset 'Line' mute
	amixer --quiet sset 'Line' 0%
	[ $? = 0 ] && echo -n "OK" || echo -n "FAIL"

	echo -n " mic - "
	amixer --quiet sset 'Mic' mute
	amixer --quiet sset 'Mic' 0%
	[ $? = 0 ] && echo -n "OK" || echo -n "FAIL"

	echo -n " speaker - "
	amixer  --quiet sset 'Speaker',0 25%
	[ $? = 0 ] && echo -n "OK" || echo -n "FAIL"

	echo " ... "

	;;
  stop)
	printf "Stopping sound: nothing to do."
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

