#!/bin/sh


start() {
	printf "Starting amplifier: "
	echo 22 > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio22/direction
	/sbin/mpc2amplifier &
	echo "OK"
}

stop() {
	printf "Stopping amplifier: "
	echo 0 > /sys/class/gpio/gpio22/value \
		&& echo "OK" || echo "FAIL"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
